services:
  - type: web
    name: talentflow
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /jobs
        destination: /index.html
      - type: rewrite
        source: /candidates
        destination: /index.html
      - type: rewrite
        source: /assessments
        destination: /index.html